name: PR Theme Management

on:
  pull_request:
    types: [opened, synchronize, reopened, closed, labeled]

# Cancel in-progress runs for the same PR
concurrency:
  group: pr-theme-${{ github.event.pull_request.number }}
  cancel-in-progress: true

# Label features:
# - Add 'rebuild-theme' label to recreate a deleted theme
# - Add 'preserve-theme' label to protect theme from auto-deletion when hitting Shopify's 20-theme limit
# - Add 'no-sync' label to skip pulling settings from production/source theme (uses repo JSON files)

jobs:
  manage-theme:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    # Security: Only run for PRs from the same repository (not forks)
    if: github.event.pull_request.head.repo.full_name == github.repository
    
    permissions:
      pull-requests: write
      issues: write
      contents: read
      
    steps:
      - name: Checkout code
        if: github.event.action != 'closed' && (github.event.action != 'labeled' || github.event.label.name == 'rebuild-theme')
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # OPTIONAL: Add build steps if your theme requires compilation
      # - name: Setup Node.js
      #   if: github.event.action != 'closed' && (github.event.action != 'labeled' || github.event.label.name == 'rebuild-theme')
      #   uses: actions/setup-node@v5
      #   with:
      #     node-version: '20'  # OPTIONAL: defaults to 20
      
      # - name: Install dependencies
      #   if: github.event.action != 'closed' && (github.event.action != 'labeled' || github.event.label.name == 'rebuild-theme')
      #   run: npm ci

      - name: Deploy/Update PR Theme
        if: github.event.action != 'closed' && (github.event.action != 'labeled' || github.event.label.name == 'rebuild-theme')
        uses: ShopLab-Team/shoplab-pr-shopify-theme-preview@v1
        with:
          # REQUIRED inputs
          github-token: ${{ secrets.GITHUB_TOKEN }}
          shopify-store-url: ${{ secrets.SHOPIFY_STORE_URL }}
          shopify-cli-theme-token: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          action-type: 'deploy'
          
          # OPTIONAL inputs (with defaults)
          # source-theme-id: '123456789'  # Theme ID to pull settings from (defaults to live theme)
          # build-command: 'npm run build'  # Command to build assets before deployment
          # theme-root: 'dist'  # Directory containing theme files (defaults to '.' repository root)
          # ignore-files: 'templates/page.instant-*.json, sections/instant-*.json'  # Patterns to ignore during upload
          # node-version: '20'  # Node.js version (defaults to 20)
          # slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}  # Slack webhook for notifications
          # ms-teams-webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}  # MS Teams webhook for notifications

      - name: Cleanup PR Theme
        if: github.event.action == 'closed'
        uses: ShopLab-Team/shoplab-pr-shopify-theme-preview@v1
        with:
          # REQUIRED inputs
          github-token: ${{ secrets.GITHUB_TOKEN }}
          shopify-store-url: ${{ secrets.SHOPIFY_STORE_URL }}
          shopify-cli-theme-token: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          action-type: 'cleanup'
          
          # OPTIONAL inputs
          # slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}  # Slack webhook for notifications
          # ms-teams-webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}  # MS Teams webhook for notifications
